### ISSUE TITLE
SpringBoot not working

### ISSUE THREAD

**Issue by neoecos** [RobWin/spring-swagger2markup-demo#2]
Hi, @RobWin 

I've been unable to boot the app.

I use the run or the runBoot tasks, after run the jar task to generate the html and pdf and I always get this.

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed May 20 11:14:14 COT 2015
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by RobWin** [comment]
Does runBoot generate a Jar file and run the AsciiDoctorJ task?
I will have a look at it tomorrow.

**Comment by RobWin** [comment]
As far as I know, `bootRun` does not create a Jar and run the asciidoctor task.
You should run `gradle build`  and start the app with `java -jar`.

**Comment by neoecos** [comment]
It's working with gradle build and then run `java -jar build/libs/spring-swagger2markup-demo-1.0.1.jar` !

**Comment by RobWin** [comment]
@neoecos You are welcome. If you like https://github.com/RobWin/swagger2markup and https://github.com/RobWin/swagger2markup-gradle-plugin, I would love to get a Star.

Do you know https://github.com/RobWin/assertj-swagger?

**Comment by RobWin** [comment]
Thx ;)

**Comment by neoecos** [comment]
Waoo, is impressive what your doing here.

I work with Grails, which does not have a good plugin for Swagger.

**Comment by RobWin** [comment]
Do you know https://github.com/springfox/springfox ?
Should work with grails.

**Comment by neoecos** [comment]
Will take a look, thanks.

**Comment by RobWin** [comment]
Join https://gitter.im/RobWin/swagger2markup if you questions or plan to use slate.

**Comment by neoecos** [comment]
@RobWin ok, lets talk in gitter
